server:
  port: 10010

spring:
  main:
    banner-mode: off
  application:
    name: '@project.artifactId@-@project.version@'
  kafka:
    bootstrap-servers: localhost:9092
  config:
    import: classpath:application-tracing.yaml

service:
  topic:
    topic-name: inbound-messages
  api:
    path: /*

logging:
  level:
    root: warn
    io:
      contino: info
