server:
  port: 10010

spring:
  application:
    name: '@project.artifactId@-@project.version@'
  kafka:
    bootstrap-servers: host.docker.internal:9092
  config:
    import: classpath:application-tracing.yaml

service:
  topic:
    topic-name: inbound-messages
  api:
    path: /*

logging:
  level:
    org:
      apache:
        kafka: warn
        kafka.clients: error
    root: warn
    io:
      contino: info
logstash:
  host: 127.0.0.1
  port: 50000
