server:
  port: 10013

spring:
  main:
    banner-mode: off
  application:
    name: '@project.artifactId@-@project.version@'
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      properties:
        spring.json.trusted.packages: "*"
  config:
    import: classpath:application-tracing.yaml

service:
  topic:
    topic-name: outbound-messages
    listener-id: store

logging:
  level:
    root: warn
    io:
      contino: info

