# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
- name: elasticsearch-v7-logstash
  orgId: 1
  
# list of datasources to insert/update depending
# what's available in the database  
# https://grafana.com/docs/grafana/latest/administration/provisioning/
datasources:
- name: elasticsearch-v7-logstash
  type: elasticsearch
  access: proxy
  database: "[logstash-]YYYY.MM.DD"
  url: http://elasticsearch:9200
  isDefault: true
  orgId: 1
  version: 1
  editable: true
  jsonData:
    interval: Daily
    timeField: "@timestamp"
    esVersion: 70
    logMessageField: message
    logLevelField: level  
