server:
  port: 10011

spring:
  main:
    banner-mode: off
  application:
    name: '@project.artifactId@-@project.version@'
  kafka:
    bootstrap-servers: localhost:9092
  config:
    import: classpath:application-tracing.yaml

service:
  inbound:
    topic:
      topic-name: inbound-messages
  outbound:
    topic:
      topic-name: outbound-messages

logging:
  level:
    root: warn
    io:
      contino: info

